### ISSUE TITLE
unicity of substitution ?

### ISSUE THREAD

**Issue by xcombelle** [sorear/metamath-turing-machines#4]
First of all you made a fantastic job. When  I eventually I beleve I understood how all worked I was impressed.

I just discovered metamath and I'm not sure I understood the code correctly so the following that I say might be totally wrong.

If I correctly read the code, the current `zf.sql` verify that a substitution exist which made the hypotheses match the entry of the stack but not that substitution is unique. According to the following quote of the metamath specification, it looks like the uniqueness is necessary.

"If the label refers to an assertion, a (unique) substitution must exist
that, when made to the mandatory hypotheses of the referenced assertion,
causes them to match the topmost (i.e. most recent) entries of the stack, in
order of occurrence of the mandatory hypotheses, with the topmost stack
entry matching the last mandatory hypothesis of the referenced assertion."

**Comment by sorear** [comment]
The other constraints in the Metamath spec (specifically, the fact that all used variables must correspond to `$f` hypotheses) guarantee that if a substitution exists, it's automatically unique; the parenthetical remark is for clarification only and is not something that needs to be checked by verifiers.

In any case, zf.nql does not follow the Metamath spec terribly closely, due to the use of tree-based Gödel codes instead of a string representation and the fact that it has no concept of a "reusable $p statement".  Proof codes in zf.nql can be as large as the 3-fold exponential of the length of the corresponding `.mm` file, but as long as we're in the constants-free world of pure computability theory that doesn't matter.

**Comment by xcombelle** [comment]
thanks a lot for anwering me. I believe the issue can be close. By the way, it took me some time to understand how your code work so I think I will document that and make a pull request to add the documentation

**Comment by sorear** [comment]
Ah, that would be very nice, thank you!  I'll take a look at that when you're ready.
